name: FTP Deploy to AnymHost

on:
  push:
    branches:
      - main        # ganti kalau pakai branch lain

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_ANYMHOST_HOST }}
        username: ${{ secrets.FTP_ANYMHOST_USER }}
        password: ${{ secrets.FTP_ANYMHOST_PASS }}
        protocol: ftp
        port: ${{ secrets.FTP_ANYMHOST_PORT }}
        local-dir: ./
        server-dir: ./
        timeout: 600000
